Shop.Web/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Web.Managers;
using Shop.Web.ViewModels.Ajax;
using Shop.SDK.Models;
using Shop.SDK.Models.Managers;
using Shop.Web.ViewModels;

namespace Shop.Web.Controllers
{
    public class BasketController : Controller
    {
        // GET: Basket
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult AjaxAddProduct(Guid productId, double count)
        {
            Guid uid = Guid.Empty;
            if (!Guid.TryParse(User.Identity.Name, out uid))
            {
                return Content(AjaxManager.SerializeAjaxAnswer(AjaxManager.CreateErrorAjaxAnswer(null, "User not found!")));
            }
            UserModel user = ManagerFactory.Instance.GetManager<UserManager>().GetById(uid) as UserModel;
            if (user == null)
            {
                return Content(AjaxManager.SerializeAjaxAnswer(AjaxManager.CreateErrorAjaxAnswer(null, "User not found!")));
            }
            var basket = ManagerFactory.Instance.GetManager<BasketManager>().GetBasketByUser(user).FirstOrDefault();
            if (basket == null)
            {
                basket = ManagerFactory.Instance.GetManager<BasketManager>().CreateBasketForUser(user);
            }
            var product = ManagerFactory.Instance.GetManager<ProductManager>().GetById(productId);
            if (product == null)
            {
                return Content(AjaxManager.SerializeAjaxAnswer(AjaxManager.CreateErrorAjaxAnswer(null, "Product not found!")));
            }
            return Content(
                AjaxManager.SerializeAjaxAnswer(
                    AjaxManager.CreateSuccessAjaxAnswer(
                        new AddProductToBasketViewModel() {
                            Basket = new BasketStatisticViewModel(basket)
                        },
                        "Товар успешно добавлен!"
                    )
                )
            );
        }
    }
}

Shop.Web/Controllers/ConsignmentController.cs
using Shop.SDK.Models;
using Shop.SDK.Models.Managers;
using Shop.Web.Managers;
using Shop.Web.ViewModels;
using Shop.Web.ViewModels.Ajax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Web.Controllers
{
    public class ConsignmentController : Controller
    {
        // GET: Consignment
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult AjaxGetProductConsignments(Guid productId)
        {
            var product = ManagerFactory.Instance.GetManager<ProductManager>().GetById(productId) as ProductModel;
            if (product == null)
            {
                return Content(AjaxManager.SerializeAjaxAnswer(AjaxManager.CreateErrorAjaxAnswer(null, "Товар не найден!")));
            }
            var cons = ManagerFactory.Instance.GetManager<ConsignmentItemManager>().GetByProduct(product);

            return Content(
                AjaxManager.SerializeAjaxAnswer(
                    AjaxManager.CreateSuccessAjaxAnswer(
                        new GetProductConsignmentsViewModel(cons)
                    )
                )
            );
        }

        [Authorize]
        [HttpGet]
        public ActionResult AjaxSelectConsignment(Guid consignmentId, Guid productId)
        {
            var product = ManagerFactory.Instance.GetManager<ProductManager>().GetById(productId) as ProductModel;
            if (product == null)
            {
                return Content(AjaxManager.SerializeAjaxAnswer(AjaxManager.CreateErrorAjaxAnswer(null, "Товар не найден!")));
            }
            var cons = product.Consignments.FirstOrDefault(_ => _.Consignment.ID == consignmentId);

            return Content(
                AjaxManager.SerializeAjaxAnswer(
                    AjaxManager.CreateSuccessAjaxAnswer(
                        new ProductConsignmentItemViewModel(cons)
                    )
                )
            );
        }
        
    }
}

Shop.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.SDK.Models.Managers;
using Shop.SDK.Models;
using Shop.Web.ViewModels;

namespace Shop.Web.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index(Guid id)
        {
            var product = ManagerFactory.Instance.GetManager<ProductManager>().GetById(id) as ProductModel;
            if (product == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(new ProductDetailsViewModel(product));
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(ProductCreationViewModel model)
        {
            if (ModelState.IsValid)
            {

            }
            return View(model);
        }

    }
}

Shop.Web/Views/Product/Create.cshtml
@using Shop.Web.Extension
@model Shop.Web.ViewModels.ProductCreationViewModel

@{ 
    var list = Shop.SDK.Models.Managers.ProductCategoryManager.GetAll();
}

@{ Html.EnableClientValidation(); }

<span>@ViewBag.ErrorMessage</span>

@using (Html.BeginForm("Create", "Product", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="item">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>
    <div class="item">
        @Html.LabelFor(model => model.Category)
        <select class="form-control" name="Category">
            @foreach(var item in list)
            {
                <option value="@item.ID">@item.Name</option>
            }
        </select>
    </div>
    <div class="item">
        @Html.LabelFor(model => model.Description)
        @Html.TextBoxFor(model => model.Description)
        @Html.ValidationMessageFor(model => model.Description)
    </div>
    <div class="item">
        @Html.LabelFor(model => model.Image)
        @Html.TextBoxFor(model => model.Image)
        @Html.ValidationMessageFor(model => model.Image)
    </div>
    <span>@Html.EditBlockFor(model => model.Category)</span>
    <input type="submit" value="Создать" />
}

Shop.Web/Views/Product/Index.cshtml
@using Shop.Web.Extension
@model Shop.Web.ViewModels.ProductDetailsViewModel

@if (Model != null)
{
    <div class="container-fluid">
        <div class="row spaced">
            <div class="container-fluid">
                <div class="col-md-2 product-details-img"> 
                    <img src="@Url.Content("~/Resources/Images/no-image-available-150.png")" />
                </div>
                <div class="col-md-8 product-details-info">
                    <div class="container-fluid">
                        <div class="form-group row">
                            <div class="col-md-3 inline-block">
                                @Html.LabelFor(model => model.Name)
                            </div>
                            <span>@Model.Name</span>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3 inline-block">
                                @Html.LabelFor(model => model.ID)
                            </div>
                            <span>@Model.ID</span>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3 inline-block">
                                @Html.LabelFor(model => model.Description)
                            </div>
                            <span>@Model.Description</span>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3 inline-block">
                                <label>Поставка</label>
                            </div>
                            <span><i>(Поставка не выбрана!)</i></span>
                            <a href="javascript:DisplayConsignments('@Model.ID');">Выбрать поставку</a>
                            @Html.EntityEditor(model => model.Consignment)
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3 inline-block">
                                <label>Количество</label>
                            </div>
                            <input class="form-control inline-block small-number" type="number" value="0" id="txtCount" min="0" max="@Model.ItemsAvailable" />
                        </div>
                        <div class="row">
                            <div class="container-fluid no-padding">
                                <button type="button" onclick="AddProductToBasket('@Model.ID');" class="btn btn-success">Добавить в корзину</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 container-fluid">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#1" data-toggle="tab">Основная информация</a>
                    </li>
                    <li>
                        <a href="#2" data-toggle="tab">Полные характеристики</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="1">
                        @Model.Description
                    </div>
                    <div class="tab-pane" id="2">
                        @{
                            var mdl = new Shop.Web.ViewModels.Categories.SpinningRodCategorySpecification();
                            @Html.CreateSpecification(mdl);
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function AddProductToBasket(id)
        {
            var count = $("#txtCount").val();
            if (count <= 0) return;
            $.ajax({
                method: "GET",
                url: "@Url.Action("AjaxAddProduct", "Basket")?productId=" + id + "&count=" + count,
                dataType: 'json',
                success: function(data)
                {
                    PopUpWindow.open('Добавление в корзину', data.Message, ((data.Success) ? "popUp-success" : "popUp-failed"));
                }
            });
        }

        function DisplayConsignments(id)
        {
            var productId = id;
            $.ajax({
                method: "GET",
                url: "@Url.Action("AjaxGetProductConsignments", "Consignment")?productId=" + productId,
                dataType: 'json',
                success: function(data)
                {
                    if (!data.Success)
                    {
                        PopUpWindow.open('Ошибка!', data.Message, "popUp-failed");
                        return;
                    }
                    var json = {};
                    json = new Array();
                    var identity = new Array();
                    for (var i = 0; i < data.Result.Items.length; i++)
                    {
                        json[i] = new Array();
                        json[i][0] = i + 1;
                        json[i][1] = data.Result.Items[i].CreationDate;
                        json[i][2] = data.Result.Items[i].Count;
                        json[i][3] = data.Result.Items[i].Cost;
                        identity[i] = data.Result.Items[i].ID;
                    }
                    console.log(json);
                    PopUpWindow.open('Выбрать поставку', '<div id="consignment_selection"></div>');
                    $("#consignment_selection").Table({
                        model: [
                            { name: "#", type: "number" },
                            { name: "Дата создания", type: "datetime" },
                            { name: "Количество на складе", type: "number", align: "center" },
                            { name: "Цена", type: "number" }
                        ],
                        data: json,
                        identity: identity,
                        rowsPerPage: 15,
                        onRowSelect: function (instance, id) {
                            PopUpWindow.close();
                            console.log(productId);
                            $.ajax({
                                method: "GET",
                                url: "@Url.Action("AjaxSelectConsignment", "Consignment")?consignmentId=" + id + "&productId=" + productId,
                                dataType: 'json',
                                success: function (data) {
                                    console.log(data);
                                    if (!data.Success) {
                                        PopUpWindow.open('Ошибка!', data.Message, "popUp-failed");
                                        return;
                                    }

                                }
                            });
                        }
                    });
                },
                failed: function () {
                    console.log('failed!');
                }
            });
        }

        function ApplyConsignment(id)
        {
            console.log(id);
        }
    </script>    
}
else
{
    <span>Продукт не найден!</span>
}

Shop.Web/Views/Product/ProductCompact.cshtml
@model Shop.Web.ViewModels.ProductDetailsViewModel

<div class="col-md-2 product-compact hoverable" onClick="window.location='@Url.Action("Index", "Product", new { id = Model.ID })'">
    <div class="image-container">
        <img class="product-image" src="~/Resources/Images/no-image-available-150.png" />
    </div>
    <h3>@Model.Name</h3>
</div>