Shop.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.SDK.Models;
using Shop.SDK.Models.Managers;
using Shop.Web.ViewModels;

namespace Shop.Web.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index(Guid id)
        {
            var category = ManagerFactory.Instance.GetManager<ProductCategoryManager>().GetById(id) as ProductCategoryModel;
            var list = new List<ProductDetailsViewModel>();
            foreach (var p in category.Products)
            {
                list.Add(new ProductDetailsViewModel(p));
            }
            return View(list);
        }
    }
}

Shop.Web/Controllers/EntityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.SDK.Models;
using Shop.SDK.Models.Managers;

namespace Shop.Web.Controllers
{
    public class EntityController : Controller
    {
        // GET: Entity
        public ActionResult Index()
        {
            return View(new UserModel());
        }
    }
}

Shop.Web/Views/Shared/Filters.cshtml
<span>filters</span>

Shop.Web/Views/Shared/Navigation.cshtml
@using Shop.SDK.Models.Managers
@using Shop.SDK.Models
@using Shop.Web.Extension
 
@helper ShowTreeNode(IEnumerable<ProductCategoryModel> list)
{

    <ul>
        @{ 
            list = list.OrderBy(x => x.Name);
        }
        @foreach (var item in list)
        {
            <li>
                @if ((item.SubCategories == null) || (item.SubCategories.Count() == 0))
                {
                    @Html.ActionLink(item.Name, "Index", "Category", new { id = item.ID }, new { })
                }
                else
                {
                    <a href="#">@item.Name</a>
                    @ShowTreeNode(item.SubCategories.OrderBy(x => x.Name))
                }
            </li>
        }
    </ul>
}

@ShowTreeNode(ManagerFactory.Instance.GetManager<ProductCategoryManager>().GetTopLevel())

Shop.Web/Views/Shared/SignInMenu.cshtml
@if (User.Identity.IsAuthenticated)
{
    <li>@Html.ActionLink(@User.Identity.Name, "UserInfo", "Account", new {   })</li>
    <li>@Html.ActionLink("Выйти", "Logout", "Account")</li>
}
else
{
    <li>@Html.ActionLink("Войти", "Index", "Account")</li>
}

Shop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Сайт</a>
                </div>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Создать", "Create", "Home")</li>
                    <li>@Html.ActionLink("Справочник", "Index", "Entity")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @Html.Partial("SignInMenu")
                </ul>
            </div>
        </nav>
        <div class="container-fluid body-content">
            <div class="row">
                <div class="col-md-2 text-left">
                    @Html.Partial("Navigation")
                </div>
                <div class="col-md-8 container-fluid">
                    @RenderBody()
                </div>
                <div class="col-md-2 text-right">
                    @Html.Partial("Filters")
                </div>
            </div>
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
        <div class="popUp-blockscreen"></div>
        <div class="popUp">
            <div class="popUp-header">
                <span></span> 
                <div class="popUp-close"><img src="/Resources/Images/close-button.png" /></div>
            </div>
            <div class="popUp-body"></div>
        </div>
        <script type="text/javascript">
            var PopUpWindow = null;
            $(document).ready(function () {
                PopUpWindow = $(".popUp").draggable().Popup();
            });
        </script>
    </div>

</body>
</html>